### PR TITLE
Implement registerUI

### PR DESCRIPTION
**Pull request by rob-3**
This PR implements the new `registerUI` function and makes a few breaking changes. Future `Command`s must destructure off their arguments as in 
```typescript
async run({ interaction, registerUI }) {
```
rather than simply taking in the interaction parameter.

This doesn't break the standard method of event handling with `Collector`s.

There are also numerous improvements to the core including extracting the interaction listening from the `Client` class, which is better suited for managing the updating and synchronization of commands with the network.

### CODE REVIEW

**Comment by suneettipirneni** [comment]
Just for assurance, has this been tested thoroughly?

**Comment by rob-3** [comment]
Probably not as extensively as I would like. I tested it with a rewritten vibe and roles command and resolved the issues I found, but mostly left other commands untouched.

**Comment by rob-3** [comment]
I keep thinking about how we can test our code in an automated way without mocking nearly everything out and I'm drawing a blank.

**Comment by suneettipirneni** [comment]
> I keep thinking about how we can test our code in an automated way without mocking nearly everything out and I'm drawing a blank.

You can't you're relying on an external api for state. You can take a look at my testing branch, to see what I've done in terms of mocking.

**Comment by rob-3** [comment]
I guess one idea is to have a separate testing bot that uses discord.js to invoke commands for itself and then checks for results, but that seems like a substantial amount of effort in itself. And I'm not sure there's any practical way to automatically click a button or select options in a menu.

**Comment by rob-3** [comment]
Ok yeah the testing branch looks like what probably is the best testing solution in terms of achievability. I just wonder if all the work mocking things out is really worthwhile for most commands. Tbh we haven't run into a ton of bugs overall. Also I always feel like the more things that are mocked, the more room there is in production for bugs to creep into the real implementations.

**Comment by rob-3** [comment]
That being said, I can write in some unit tests for a lot of the mostly pure functions like `registerUI()` that don't really need to talk to the outside world.

**Review by suneettipirneni — APPROVED** [review]

**Pull request merged**
