### PR TITLE
Add button interactions

### PR DESCRIPTION
**Pull request by suneettipirneni**
This adds button interactions via a listener object attached to each command, here's an example of how it works:
```ts

// commands/testCommand.ts

import { CommandInteraction, MessageActionRow, MessageButton } from 'discord.js';
import { ButtonListener, Command } from 'dispatch';

// Create row.
const row: MessageActionRow = new MessageActionRow();

// Create button.
const button = new MessageButton({
  label: 'Say Hello!',
  style: 'PRIMARY',
  customId: 'myID',
});

// Add button to row
row.addComponents(button);

// Create listener for button interactions.
const listener = new ButtonListener();

// Register handlers.
listener.on('myID', (interaction) => {
  interaction.reply(`Hello ${interaction.user.username}!`);
});

// Create command.
const command: Command = {
  name: 'test',
  description: 'a test command',
  async run(interaction: CommandInteraction): Promise<void> {
    await interaction.reply({ content: 'hello', components: [row]});
  },
  buttonListener: listener,
};

export default command;

```

This example results in this behavior:

Screen Shot 2021-07-12 at 4 59 31 PM

### CODE REVIEW

**Review by rob-3 — APPROVED** [review]

**Comment by rob-3** [comment]
This seems to work fine, but the API for plugin authors is still a bit clunky. Do you think we could make it so you could write something like this:
```typescript
// commands/testCommand.ts

// Pick a better name for this type
const buttons: OurButton[] = [
  {
    label: "Say Hello!",
    style: "PRIMARY",
    onClick: (interaction) => {
      interaction.reply(`Hello ${interaction.user.username}!`);
    },
  },
  {
    label: "Say Goodbye!",
    style: "PRIMARY",
    onClick: (interaction) => {
      interaction.reply(`Goodbye ${interaction.user.username}!`);
    },
  },
];

// Create command.
const command: ButtonCommand = {
  name: "test",
  description: "a test command",
  // not sure exactly how we want to implement this
  // but we should maintain the ability to dynamically generate buttons
  // and also consider a wrapper API
  run: async (interaction) => {
    await interaction.reply({content: "hello", components: toComponents(buttons)})
  },
};

export default command;

```

**Comment by suneettipirneni** [comment]
> This seems to work fine, but the API for plugin authors is still a bit clunky. Do you think we could make it so you could write something like this:
> 
> ```ts
> // commands/testCommand.ts
> 
> // Pick a better name for this type
> const buttons: OurButton[] = [
>   {
>     label: "Say Hello!",
>     style: "PRIMARY",
>     onClick: (interaction) => {
>       interaction.reply(`Hello ${interaction.user.username}!`);
>     },
>   },
>   {
>     label: "Say Goodbye!",
>     style: "PRIMARY",
>     onClick: (interaction) => {
>       interaction.reply(`Goodbye ${interaction.user.username}!`);
>     },
>   },
> ];
> 
> // Create command.
> const command: ButtonCommand = {
>   name: "test",
>   description: "a test command",
>   // not sure exactly how we want to implement this
>   // but we should maintain the ability to dynamically generate buttons
>   // and also consider a wrapper API
>   run: async (interaction) => {
>     await interaction.reply({content: "hello", components: toComponents(buttons)})
>   },
> };
> 
> export default command;
> ```

hmm, perhaps I'll look into this.

**Comment by rob-3** [comment]
It feels a bit awkward to have to manually deal with the ids.

**Comment by suneettipirneni** [comment]
> It feels a bit awkward to have to manually deal with the ids.

I mean that's a limitation of the discord api, you have to use ID's for it to know exactly *which* button is pressed.

**Comment by rob-3** [comment]
Right but we can generate the ids behind the scenes in dispatch so the user doesn't have to think about it. I'll try to work on this after I finish my work on the roles permissions and see what I can do. It should be possible to do this.

**Pull request merged**
